// ============================================================
// FRASES-CINE.JS — Banco de 200 frases motivacionales del cine
// Fuente: "200 frases motivacionales inspiradas en el cine" (PDF de Memo, 24-jul-2026).
// Son PARÁFRASIS ORIGINALES inspiradas en los arcos de los personajes,
// no transcripciones literales de diálogos (así lo indica la fuente).
// Campos: f = frase · p = película · c = personaje · t = tono
//   t: 'animo' = para días pesados (levantarse, esperanza, resiliencia)
//      'foco'  = para días normales (disciplina, constancia, trabajo)
//      'poder' = para días a tope (sueños grandes, atreverse, conquistar)
// Se carga ANTES de kamehouse.js (window.FRASES_CINE).
// ============================================================
window.FRASES_CINE = [
{f:"La esperanza puede aparecer incluso cuando todo parece perdido.",p:"Harry Potter and the Prisoner of Azkaban",c:"Albus Dumbledore",t:"animo"},
{f:"No importa cuántas veces caigas: tu historia cambia cada vez que vuelves a levantarte.",p:"Rocky",c:"Rocky Balboa",t:"animo"},
{f:"La vida sigue avanzando; tu poder está en decidir cómo caminar con ella.",p:"Forrest Gump",c:"Forrest Gump",t:"foco"},
{f:"Tus circunstancias explican el comienzo, pero no tienen derecho a decidir el final.",p:"The Pursuit of Happyness",c:"Chris Gardner",t:"animo"},
{f:"Un paso pequeño puede ser el inicio de la aventura más grande de tu vida.",p:"The Hobbit: An Unexpected Journey",c:"Bilbo Baggins",t:"poder"},
{f:"El miedo pierde fuerza cuando dejas de huir y decides mirarlo de frente.",p:"Batman Begins",c:"Bruce Wayne",t:"animo"},
{f:"Lo que haces hoy puede abrir un futuro que todavía no alcanzas a imaginar.",p:"Back to the Future",c:"Marty McFly",t:"poder"},
{f:"La grandeza no depende de tu origen, sino de lo que te atreves a crear.",p:"Ratatouille",c:"Remy",t:"poder"},
{f:"No necesitas ser perfecto para construir algo extraordinario.",p:"Iron Man",c:"Tony Stark",t:"foco"},
{f:"Incluso la persona más pequeña puede cambiar el rumbo de una historia enorme.",p:"The Lord of the Rings: The Fellowship of the Ring",c:"Frodo Baggins",t:"poder"},
{f:"Tu pasado forma parte de ti, pero no tiene que gobernar tus decisiones.",p:"The Lion King",c:"Simba",t:"animo"},
{f:"Los sueños necesitan talento, disciplina y el valor de parecer un poco loco.",p:"La La Land",c:"Mia Dolan",t:"poder"},
{f:"La verdadera fuerza aparece justo cuando pensabas que ya no te quedaba ninguna.",p:"Gladiator",c:"Maximus Decimus Meridius",t:"animo"},
{f:"No esperes a sentirte listo: empieza y deja que el camino te enseñe.",p:"Star Wars: A New Hope",c:"Luke Skywalker",t:"foco"},
{f:"Aquello que te hace diferente también puede convertirse en tu forma de volar.",p:"Dumbo",c:"Dumbo",t:"poder"},
{f:"El talento puede abrir una puerta, pero la práctica decide cuánto tiempo permanece abierta.",p:"Whiplash",c:"Andrew Neiman",t:"foco"},
{f:"Mientras sigas buscando una salida, la tormenta todavía no ha ganado.",p:"Cast Away",c:"Chuck Noland",t:"animo"},
{f:"Cambiar de dirección no significa fracasar; a veces significa comprender lo que realmente importa.",p:"Cars",c:"Lightning McQueen",t:"animo"},
{f:"No puedes controlar todo lo que sucede, pero sí la actitud con la que respondes.",p:"Kung Fu Panda",c:"Po",t:"foco"},
{f:"Muchos límites existen primero en la mente antes de convertirse en realidad.",p:"The Matrix",c:"Neo",t:"poder"},
{f:"La vida comienza de verdad cuando dejas de actuar para los demás.",p:"The Truman Show",c:"Truman Burbank",t:"foco"},
{f:"Una sola decisión valiente puede romper años enteros de miedo.",p:"Brave",c:"Merida",t:"poder"},
{f:"No permitas que nadie reduzca el tamaño de tus sueños para sentirse cómodo.",p:"Little Women",c:"Jo March",t:"poder"},
{f:"A veces tienes que perderte para descubrir la versión de ti que estaba esperando salir.",p:"Alice in Wonderland",c:"Alice Kingsleigh",t:"animo"},
{f:"La familia también puede ser la gente que decide quedarse cuando todo se complica.",p:"Lilo & Stitch",c:"Stitch",t:"animo"},
{f:"Nunca es demasiado tarde para aprender algo nuevo o comenzar una etapa distinta.",p:"The Intern",c:"Ben Whittaker",t:"foco"},
{f:"Tus cicatrices no te hacen débil; cuentan todo lo que fuiste capaz de sobrevivir.",p:"The Revenant",c:"Hugh Glass",t:"animo"},
{f:"La disciplina sigue trabajando cuando la motivación ya se fue a dormir.",p:"Creed",c:"Adonis Creed",t:"foco"},
{f:"Un sueño imposible puede convertirse en un plan cuando empiezas a estudiar cómo lograrlo.",p:"October Sky",c:"Homer Hickam",t:"poder"},
{f:"El éxito empieza el día en que dejas de pedir permiso para creer en ti.",p:"Legally Blonde",c:"Elle Woods",t:"poder"},
{f:"Lo que otros consideran extraño puede ser exactamente lo que te vuelve inolvidable.",p:"Edward Scissorhands",c:"Edward Scissorhands",t:"poder"},
{f:"El dolor puede encerrarte o convertirse en la fuerza que te ayude a salir.",p:"The Dark Knight Rises",c:"Bruce Wayne",t:"animo"},
{f:"No necesitas ver el océano completo para confiar en el siguiente movimiento.",p:"Moana",c:"Moana",t:"foco"},
{f:"El mundo cambia cuando alguien se atreve a imaginar algo que todavía no existe.",p:"Willy Wonka & the Chocolate Factory",c:"Willy Wonka",t:"poder"},
{f:"Siempre hay una posibilidad mientras te niegues a aceptar que todo terminó.",p:"Mission: Impossible",c:"Ethan Hunt",t:"animo"},
{f:"Tu voz merece ser escuchada, incluso cuando al principio salga temblando.",p:"The King's Speech",c:"King George VI",t:"animo"},
{f:"La competencia más importante es contra la persona que fuiste ayer.",p:"Chariots of Fire",c:"Eric Liddell",t:"foco"},
{f:"Aceptar ayuda no te hace menos fuerte; te hace lo bastante valiente para avanzar.",p:"Good Will Hunting",c:"Will Hunting",t:"animo"},
{f:"No eres el peor error que cometiste, sino lo que decides hacer después.",p:"Spider-Man",c:"Peter Parker",t:"animo"},
{f:"Algunas batallas se ganan manteniéndote fiel a tus principios un día más.",p:"Hacksaw Ridge",c:"Desmond Doss",t:"foco"},
{f:"La curiosidad puede llevarte a lugares que el miedo nunca se atrevería a visitar.",p:"Up",c:"Carl Fredricksen",t:"poder"},
{f:"La imaginación es el primer plano de todo aquello que algún día podría construirse.",p:"The Greatest Showman",c:"P. T. Barnum",t:"poder"},
{f:"El fracaso es información: úsala para volver a intentarlo de una manera más inteligente.",p:"Moneyball",c:"Billy Beane",t:"foco"},
{f:"Una mente enfocada puede encontrar patrones donde los demás solamente ven caos.",p:"A Beautiful Mind",c:"John Nash",t:"foco"},
{f:"La bondad puede cambiar una habitación antes de que alguien note lo que ocurrió.",p:"Paddington",c:"Paddington Brown",t:"foco"},
{f:"Tu propósito no siempre está escondido en el futuro; a veces ya vive en lo cotidiano.",p:"Soul",c:"Joe Gardner",t:"foco"},
{f:"Ganar no sirve de nada si para hacerlo pierdes aquello que te hacía humano.",p:"The Hunger Games",c:"Katniss Everdeen",t:"foco"},
{f:"La libertad empieza cuando dejas de vivir conforme a los planes que otros hicieron para ti.",p:"Billy Elliot",c:"Billy Elliot",t:"poder"},
{f:"Salir de lo conocido puede enseñarte cosas que ningún mapa contiene.",p:"Into the Wild",c:"Christopher McCandless",t:"poder"},
{f:"Los buenos amigos te recuerdan quién eres cuando tú mismo empiezas a olvidarlo.",p:"Toy Story",c:"Woody",t:"animo"},
{f:"Una persona decidida puede incomodar a un sistema entero hasta obligarlo a cambiar.",p:"Erin Brockovich",c:"Erin Brockovich",t:"poder"},
{f:"Tu verdadero valor aparece cuando eliges tu propio camino en lugar del que esperaban de ti.",p:"Mulan",c:"Mulan",t:"poder"},
{f:"El coraje no elimina el miedo; solamente evita que sea quien tome la decisión.",p:"Wonder Woman",c:"Diana Prince",t:"animo"},
{f:"El talento necesita oportunidades, pero también necesita a alguien dispuesto a derribar puertas.",p:"Hidden Figures",c:"Katherine Johnson",t:"poder"},
{f:"Tu origen no limita el destino que puedes construir con perseverancia.",p:"Slumdog Millionaire",c:"Jamal Malik",t:"poder"},
{f:"La paciencia y la repetición convierten movimientos torpes en verdadera habilidad.",p:"The Karate Kid",c:"Daniel LaRusso",t:"foco"},
{f:"Dominarte a ti mismo puede ser más poderoso que vencer a cualquier adversario.",p:"Kung Fu Panda 2",c:"Po",t:"foco"},
{f:"Reconstruirte no significa olvidar lo perdido, sino aprender a vivir sin rendirte.",p:"Manchester by the Sea",c:"Lee Chandler",t:"animo"},
{f:"Dejar de compararte puede ser el primer paso para descubrir quién eres realmente.",p:"Barbie",c:"Barbie",t:"animo"},
{f:"Las oportunidades suelen aparecer cuando te atreves a correr detrás de ellas.",p:"Catch Me If You Can",c:"Frank Abagnale Jr.",t:"poder"},
{f:"Una idea puede sobrevivir a quienes intentan silenciarla.",p:"V for Vendetta",c:"Evey Hammond",t:"poder"},
{f:"Cada día puede ser distinto cuando tú eliges responder de una manera nueva.",p:"Groundhog Day",c:"Phil Connors",t:"foco"},
{f:"Resolver un gran problema empieza por dividirlo en el siguiente problema posible.",p:"The Martian",c:"Mark Watney",t:"foco"},
{f:"El conocimiento abre caminos que la fuerza por sí sola nunca podría cruzar.",p:"The Imitation Game",c:"Alan Turing",t:"foco"},
{f:"Liderar no es ocupar el lugar más alto, sino proteger a quienes confían en ti.",p:"Black Panther",c:"T'Challa",t:"foco"},
{f:"Recordar de dónde vienes puede devolverte la fuerza para continuar.",p:"Coco",c:"Miguel Rivera",t:"animo"},
{f:"Los sueños comienzan a moverse cuando dejas de imaginarlos y empiezas a practicarlos.",p:"Flashdance",c:"Alex Owens",t:"foco"},
{f:"La adversidad revela capacidades que la comodidad mantiene escondidas.",p:"127 Hours",c:"Aron Ralston",t:"animo"},
{f:"A veces debes saltar antes de saber exactamente dónde vas a aterrizar.",p:"Spider-Man: Into the Spider-Verse",c:"Miles Morales",t:"poder"},
{f:"Nunca es demasiado tarde para decir lo que sientes y cuidar el tiempo que compartes.",p:"About Time",c:"Tim Lake",t:"animo"},
{f:"Ser auténtico puede llevarte más lejos que intentar agradarle a todo el mundo.",p:"Shrek",c:"Shrek",t:"foco"},
{f:"La excelencia se construye con cientos de decisiones pequeñas que nadie aplaude.",p:"The Last Samurai",c:"Nathan Algren",t:"foco"},
{f:"No tienes que salvar a todo el mundo para cambiar por completo la vida de alguien.",p:"Schindler's List",c:"Oskar Schindler",t:"foco"},
{f:"La confianza nace cuando cumples, una y otra vez, las promesas que te haces.",p:"Top Gun: Maverick",c:"Pete 'Maverick' Mitchell",t:"foco"},
{f:"Toda aventura importante exige aceptar una parte de incertidumbre.",p:"Raiders of the Lost Ark",c:"Indiana Jones",t:"poder"},
{f:"Algunas puertas se abren cuando finalmente dejas de tener miedo de ser tú.",p:"Frozen",c:"Elsa",t:"poder"},
{f:"Las diferencias pueden unirnos cuando aprendemos a conocerlas en lugar de temerlas.",p:"Zootopia",c:"Judy Hopps",t:"foco"},
{f:"Un fracaso profesional no cancela tu talento; puede obligarte a recuperar tu pasión.",p:"Chef",c:"Carl Casper",t:"animo"},
{f:"Defender lo correcto puede dejarte solo por un momento, pero nunca te vuelve insignificante.",p:"12 Angry Men",c:"Juror 8",t:"foco"},
{f:"La esperanza mantiene abierta una puerta que la desesperación intenta cerrar.",p:"The Shawshank Redemption",c:"Andy Dufresne",t:"animo"},
{f:"Tu historia puede inspirar a otros incluso antes de que llegue la victoria.",p:"Unbroken",c:"Louis Zamperini",t:"animo"},
{f:"Volver a jugar puede devolverte una parte de ti que habías olvidado.",p:"Big",c:"Josh Baskin",t:"animo"},
{f:"Una derrota no tiene por qué convencerte de abandonar la carrera.",p:"Rush",c:"Niki Lauda",t:"animo"},
{f:"Amar también significa aceptar que no puedes controlar cada despedida.",p:"Interstellar",c:"Joseph Cooper",t:"animo"},
{f:"La vida puede ser imperfecta y aun así estar llena de momentos memorables.",p:"Little Miss Sunshine",c:"Olive Hoover",t:"animo"},
{f:"Escuchar tu intuición puede llevarte hacia un camino que nadie más entiende todavía.",p:"Pocahontas",c:"Pocahontas",t:"poder"},
{f:"La vida se expande cuando dejas de observarla desde lejos y decides participar.",p:"The Secret Life of Walter Mitty",c:"Walter Mitty",t:"foco"},
{f:"Nadie puede detener a una persona que finalmente decidió cambiar su propia historia.",p:"Joy",c:"Joy Mangano",t:"poder"},
{f:"El miedo se vuelve más pequeño cuando tu propósito se vuelve más grande.",p:"Dune",c:"Paul Atreides",t:"poder"},
{f:"No necesitas hacerlo todo perfecto para crear algo que valga la pena.",p:"The Mitchells vs. the Machines",c:"Katie Mitchell",t:"foco"},
{f:"Las personas correctas pueden devolverte el sentido de pertenencia.",p:"Guardians of the Galaxy",c:"Peter Quill",t:"animo"},
{f:"Algunas respuestas aparecen cuando aprendes a escuchar antes de reaccionar.",p:"Peaceful Warrior",c:"Dan Millman",t:"foco"},
{f:"Comprender el tiempo puede enseñarte a valorar cada conversación antes de que termine.",p:"Arrival",c:"Louise Banks",t:"foco"},
{f:"La derrota de hoy puede convertirse en el entrenamiento que necesitabas para mañana.",p:"Rocky Balboa",c:"Rocky Balboa",t:"animo"},
{f:"La vida cambia cuando dejas de sobrevivir en automático y empiezas a elegir con intención.",p:"Eat Pray Love",c:"Elizabeth Gilbert",t:"foco"},
{f:"No todos los héroes llevan capa; muchos simplemente cumplen su palabra.",p:"Superman",c:"Clark Kent",t:"foco"},
{f:"Tu mejor versión no aparece de repente: se construye con cada entrenamiento.",p:"Creed II",c:"Adonis Creed",t:"foco"},
{f:"El futuro pertenece a quienes se atreven a imaginarlo antes que los demás.",p:"Tomorrowland",c:"Casey Newton",t:"poder"},
{f:"Sigue adelante: tal vez la mejor escena de tu historia todavía no ha comenzado.",p:"Cinema Paradiso",c:"Salvatore Di Vita",t:"animo"},
{f:"La constancia puede mantener vivo un propósito incluso cuando el camino parece interminable.",p:"The Princess Bride",c:"Westley",t:"foco"},
{f:"Las palabras adecuadas pueden despertar en alguien el valor que llevaba años dormido.",p:"Dead Poets Society",c:"John Keating",t:"foco"},
{f:"Una persona que cree en sus estudiantes puede cambiar el destino de un salón entero.",p:"Freedom Writers",c:"Erin Gruwell",t:"foco"},
{f:"Un equipo empieza a ganar cuando deja de pensar en colores distintos y reconoce una meta común.",p:"Remember the Titans",c:"Herman Boone",t:"foco"},
{f:"La disciplina no es castigo; es la estructura que protege tus objetivos.",p:"Coach Carter",c:"Ken Carter",t:"foco"},
{f:"Un sueño puede parecer absurdo hasta que tu constancia obliga a los demás a tomarlo en serio.",p:"Rudy",c:"Rudy Ruettiger",t:"poder"},
{f:"Que alguien crea en ti puede ayudarte, pero aprender a creer en ti mismo transforma todo.",p:"The Blind Side",c:"Michael Oher",t:"animo"},
{f:"Las expectativas pequeñas no deben limitar el esfuerzo de una comunidad grande.",p:"McFarland, USA",c:"Jim White",t:"poder"},
{f:"El perdón puede unir a un país cuando la venganza solamente prolongaría la herida.",p:"Invictus",c:"Nelson Mandela",t:"foco"},
{f:"La pelea más importante puede ser contra la voz interna que te dice que ya es demasiado tarde.",p:"The Fighter",c:"Micky Ward",t:"animo"},
{f:"Tener una oportunidad significa estar dispuesto a trabajar cuando nadie está mirando.",p:"Million Dollar Baby",c:"Maggie Fitzgerald",t:"foco"},
{f:"La dignidad no depende de cuánto tienes, sino de cuánto resistes sin perderte.",p:"Cinderella Man",c:"James J. Braddock",t:"animo"},
{f:"A veces dos seres lastimados encuentran fuerzas al aprender a confiar uno en el otro.",p:"Seabiscuit",c:"Red Pollard",t:"animo"},
{f:"La velocidad importa, pero comprender a tu equipo puede llevarte hasta la meta.",p:"Ford v Ferrari",c:"Ken Miles",t:"foco"},
{f:"Nunca es demasiado tarde para perseguir la marca que llevas toda la vida imaginando.",p:"The World's Fastest Indian",c:"Burt Munro",t:"poder"},
{f:"No necesitas el cuerpo ideal para tener el valor de presentarte en la competencia.",p:"Eddie the Eagle",c:"Eddie Edwards",t:"poder"},
{f:"La meta no siempre es ganar una medalla; a veces es demostrar que mereces estar ahí.",p:"Cool Runnings",c:"Derice Bannock",t:"poder"},
{f:"El mundo puede subestimarte hasta el momento exacto en que decides demostrar tu nivel.",p:"A League of Their Own",c:"Dottie Hinson",t:"poder"},
{f:"Tu pasión merece espacio incluso cuando las tradiciones intentan reducirlo.",p:"Bend It Like Beckham",c:"Jess Bhamra",t:"poder"},
{f:"Un sueño antiguo todavía puede encontrar una segunda oportunidad.",p:"The Rookie",c:"Jim Morris",t:"animo"},
{f:"Creer en una posibilidad puede cambiar la historia de todos los que apostaron por ella.",p:"Secretariat",c:"Penny Chenery",t:"poder"},
{f:"Una idea sencilla puede iluminar una comunidad cuando nace de observar y aprender.",p:"The Boy Who Harnessed the Wind",c:"William Kamkwamba",t:"poder"},
{f:"El cuerpo puede tener límites, pero la curiosidad siempre puede seguir viajando.",p:"The Theory of Everything",c:"Stephen Hawking",t:"animo"},
{f:"Un talento extraordinario merece paciencia, guía y un lugar donde crecer.",p:"The Man Who Knew Infinity",c:"Srinivasa Ramanujan",t:"foco"},
{f:"Construir algo grande también exige aprender a cuidar a las personas que te acompañaron.",p:"The Social Network",c:"Mark Zuckerberg",t:"foco"},
{f:"Las ideas poderosas necesitan claridad, insistencia y el valor de decir que algo aún no es suficiente.",p:"Steve Jobs",c:"Steve Jobs",t:"foco"},
{f:"La perseverancia abre puertas, pero el carácter decide qué haces después de cruzarlas.",p:"The Founder",c:"Ray Kroc",t:"foco"},
{f:"Una gran apuesta comienza cuando alguien ve valor donde los demás solamente ven riesgo.",p:"Air",c:"Sonny Vaccaro",t:"poder"},
{f:"La creatividad también consiste en encontrar una salida cuando las reglas parecen imposibles.",p:"Tetris",c:"Henk Rogers",t:"poder"},
{f:"Pensar diferente puede parecer una locura hasta que los números empiezan a darte la razón.",p:"The Big Short",c:"Michael Burry",t:"poder"},
{f:"La inteligencia puede romper barreras cuando se combina con estrategia y paciencia.",p:"The Banker",c:"Bernard Garrett",t:"foco"},
{f:"No necesitas pertenecer al club para demostrar que puedes competir al máximo nivel.",p:"The Greatest Game Ever Played",c:"Francis Ouimet",t:"poder"},
{f:"Un sueño imposible se vuelve alcanzable cuando lo conviertes en preparación diaria.",p:"The Walk",c:"Philippe Petit",t:"foco"},
{f:"La calma en medio del caos puede salvar más que cualquier reacción impulsiva.",p:"Sully",c:"Chesley Sullenberger",t:"foco"},
{f:"Cuando un plan falla, la creatividad y el trabajo en equipo pueden traer a todos de regreso.",p:"Apollo 13",c:"Jim Lovell",t:"animo"},
{f:"Los pasos históricos suelen comenzar con años de trabajo silencioso.",p:"First Man",c:"Neil Armstrong",t:"foco"},
{f:"Los límites se mueven cuando alguien se atreve a probar lo que todavía parece imposible.",p:"The Right Stuff",c:"Chuck Yeager",t:"poder"},
{f:"La estrategia puede transformar una desventaja en una nueva manera de ver el tablero.",p:"Queen of Katwe",c:"Phiona Mutesi",t:"foco"},
{f:"Tu voz merece un lugar incluso en espacios donde nadie esperaba escucharte.",p:"Akeelah and the Bee",c:"Akeelah Anderson",t:"poder"},
{f:"La verdadera capacidad no siempre se mide por la edad, sino por la profundidad con la que comprendes.",p:"Gifted",c:"Mary Adler",t:"poder"},
{f:"Un mentor puede mostrarte una puerta, pero tú debes decidir atravesarla.",p:"Finding Forrester",c:"Jamal Wallace",t:"foco"},
{f:"Las ideas bien defendidas pueden cambiar una sala antes de cambiar al mundo.",p:"The Great Debaters",c:"Melvin B. Tolson",t:"poder"},
{f:"Contar la verdad puede ser el primer paso para transformar una injusticia normalizada.",p:"The Help",c:"Aibileen Clark",t:"foco"},
{f:"Sobrevivir no es el final: también mereces aprender a vivir con alegría.",p:"The Color Purple",c:"Celie Harris-Johnson",t:"animo"},
{f:"La compasión puede seguir siendo poderosa incluso en los lugares más crueles.",p:"The Green Mile",c:"John Coffey",t:"foco"},
{f:"Una amistad inesperada puede devolverte las ganas de participar en tu propia vida.",p:"The Intouchables",c:"Philippe",t:"animo"},
{f:"Tu sueño merece respeto, aunque los demás solo vean tus limitaciones.",p:"The Peanut Butter Falcon",c:"Zak",t:"poder"},
{f:"Elegir tu voz no significa dejar de amar a tu familia.",p:"CODA",c:"Ruby Rossi",t:"animo"},
{f:"Ayudar a alguien también puede enseñarte a reparar tus propias heridas.",p:"The Fundamentals of Caring",c:"Ben Benjamin",t:"animo"},
{f:"No esperes al último capítulo para empezar a vivir las experiencias que deseas.",p:"The Bucket List",c:"Carter Chambers",t:"poder"},
{f:"Comenzar de nuevo puede ser aterrador, pero también puede devolverte la curiosidad.",p:"The Best Exotic Marigold Hotel",c:"Evelyn Greenslade",t:"animo"},
{f:"La historia que cuentas sobre tu vida puede ayudarte a atravesar lo imposible.",p:"Life of Pi",c:"Pi Patel",t:"animo"},
{f:"En medio del desastre, el amor puede convertirse en una brújula.",p:"The Impossible",c:"Maria Bennett",t:"animo"},
{f:"Encontrar tus raíces puede ayudarte a comprender el camino que ya recorriste.",p:"Lion",c:"Saroo Brierley",t:"animo"},
{f:"La valentía también consiste en proteger vidas cuando el miedo domina la calle.",p:"Hotel Rwanda",c:"Paul Rusesabagina",t:"foco"},
{f:"Viajar puede cambiar tus ideas cuando te permites escuchar las historias de otros.",p:"The Motorcycle Diaries",c:"Ernesto Guevara",t:"poder"},
{f:"Un camino difícil puede ayudarte a hacer las paces con aquello que no pudiste cambiar.",p:"The Way",c:"Tom Avery",t:"animo"},
{f:"Caminar hacia adelante puede ser una manera de dejar de huir de ti mismo.",p:"Wild",c:"Cheryl Strayed",t:"animo"},
{f:"La soledad elegida puede enseñarte de qué estás hecha cuando todo depende de ti.",p:"Tracks",c:"Robyn Davidson",t:"animo"},
{f:"La montaña no negocia, pero puede enseñarte humildad, preparación y respeto.",p:"Everest",c:"Rob Hall",t:"foco"},
{f:"Mientras puedas tomar una decisión más, todavía existe una posibilidad de salir.",p:"Touching the Void",c:"Joe Simpson",t:"animo"},
{f:"La libertad se vuelve una meta real cuando cada paso está sostenido por esperanza.",p:"The Way Back",c:"Janusz Wieszczek",t:"animo"},
{f:"Una convicción puede cruzar océanos cuando está respaldada por preparación.",p:"Kon-Tiki",c:"Thor Heyerdahl",t:"poder"},
{f:"El valor no elimina la tormenta; te ayuda a entrar en ella por una razón correcta.",p:"The Finest Hours",c:"Bernie Webber",t:"foco"},
{f:"En una emergencia, cada decisión clara puede convertirse en una vida salvada.",p:"Deepwater Horizon",c:"Mike Williams",t:"foco"},
{f:"El compañerismo se demuestra cuando decides correr hacia el peligro por los demás.",p:"Only the Brave",c:"Eric Marsh",t:"foco"},
{f:"La experiencia, la paciencia y el trabajo en equipo pueden encontrar una salida bajo tierra.",p:"Thirteen Lives",c:"Rick Stanton",t:"foco"},
{f:"La esperanza puede sobrevivir incluso cuando el mundo intenta convencerte de lo contrario.",p:"Rescue Dawn",c:"Dieter Dengler",t:"animo"},
{f:"Mantener la calma puede ser la diferencia entre el pánico y la supervivencia.",p:"Captain Phillips",c:"Richard Phillips",t:"foco"},
{f:"Entrenar a otros también puede enseñarte qué heridas todavía necesitas enfrentar.",p:"The Guardian",c:"Ben Randall",t:"animo"},
{f:"La perseverancia puede abrir un camino incluso dentro de instituciones que no quieren cambiar.",p:"Men of Honor",c:"Carl Brashear",t:"poder"},
{f:"Tu historia no tiene por qué estar definida por lo peor que te sucedió.",p:"Antwone Fisher",c:"Antwone Fisher",t:"animo"},
{f:"La conexión humana puede sobrevivir a la pobreza, la enfermedad y el ruido de una gran ciudad.",p:"The Soloist",c:"Nathaniel Ayers",t:"animo"},
{f:"La empatía también puede ser una forma seria y poderosa de sanar.",p:"Patch Adams",c:"Patch Adams",t:"foco"},
{f:"A veces un pequeño avance significa devolverle a alguien una parte entera de su mundo.",p:"Awakenings",c:"Dr. Malcolm Sayer",t:"foco"},
{f:"Comprender el miedo de un paciente puede cambiar la manera en que practicas tu profesión.",p:"The Doctor",c:"Jack McKee",t:"foco"},
{f:"La habilidad crece cuando la curiosidad se combina con disciplina y servicio.",p:"Gifted Hands: The Ben Carson Story",c:"Ben Carson",t:"foco"},
{f:"El talento puede prosperar incluso cuando el reconocimiento llega demasiado tarde.",p:"Something the Lord Made",c:"Vivien Thomas",t:"animo"},
{f:"Comprender tu manera distinta de pensar puede convertirse en una ventaja extraordinaria.",p:"Temple Grandin",c:"Temple Grandin",t:"poder"},
{f:"La amistad y la inclusión pueden devolverle dignidad a quien fue ignorado.",p:"Radio",c:"James Robert Kennedy",t:"animo"},
{f:"No necesitas ocultar lo que te hace diferente para demostrar tu capacidad.",p:"Front of the Class",c:"Brad Cohen",t:"poder"},
{f:"Tu rostro no determina el tamaño de tu corazón ni el lugar que mereces ocupar.",p:"Wonder",c:"Auggie Pullman",t:"animo"},
{f:"Pedir ayuda puede ser el primer acto de valentía cuando te sientes invisible.",p:"The Perks of Being a Wallflower",c:"Charlie Kelmeckis",t:"animo"},
{f:"Crecer también consiste en aceptar que no tienes todas las respuestas.",p:"The Edge of Seventeen",c:"Nadine Franklin",t:"animo"},
{f:"Alejarte de casa puede ayudarte a valorar de dónde vienes sin dejar de elegir quién serás.",p:"Lady Bird",c:"Christine 'Lady Bird' McPherson",t:"foco"},
{f:"El esfuerzo también merece espacio para la amistad, la risa y la improvisación.",p:"Booksmart",c:"Molly Davidson",t:"foco"},
{f:"No tienes que encajar en una etiqueta para descubrir quién eres.",p:"The Breakfast Club",c:"Brian Johnson",t:"poder"},
{f:"La vida ocurre ahora; no la pierdas esperando el momento perfecto.",p:"Ferris Bueller's Day Off",c:"Ferris Bueller",t:"poder"},
{f:"Una persona puede ayudarte a salir de tu caparazón sin obligarte a dejar de ser tú.",p:"The Way Way Back",c:"Duncan",t:"animo"},
{f:"Encontrar una familia inesperada puede cambiar tu idea de pertenencia.",p:"Hunt for the Wilderpeople",c:"Ricky Baker",t:"animo"},
{f:"Crear algo propio puede ser la salida cuando el mundo alrededor parece detenido.",p:"Sing Street",c:"Conor Lalor",t:"poder"},
{f:"Un nuevo comienzo puede surgir cuando compartes tu arte con la persona correcta.",p:"Begin Again",c:"Gretta James",t:"poder"},
{f:"El talento encuentra caminos incluso cuando nadie entiende todavía de dónde viene.",p:"August Rush",c:"Evan Taylor",t:"poder"},
{f:"Enseñar con pasión puede despertar habilidades que una clase tradicional nunca vio.",p:"School of Rock",c:"Dewey Finn",t:"foco"},
{f:"La alegría puede ser contagiosa cuando alguien se atreve a romper la rutina.",p:"Sister Act",c:"Deloris Van Cartier",t:"poder"},
{f:"Una segunda oportunidad creativa puede aparecer cuando dejas de fingir que ya no te importa.",p:"Music and Lyrics",c:"Alex Fletcher",t:"animo"},
{f:"Una canción honesta puede conectar a dos personas antes de que sepan cómo nombrar lo que sienten.",p:"Once",c:"The Guy",t:"animo"},
{f:"Un proyecto necesita más que talento: necesita dirección, hambre y gente dispuesta a creer.",p:"The Commitments",c:"Jimmy Rabbitte",t:"foco"},
{f:"La música puede darte palabras para comprender el lugar donde creciste.",p:"Blinded by the Light",c:"Javed Khan",t:"animo"},
{f:"El éxito pierde sentido cuando deja de estar conectado con la verdad de quien eres.",p:"Yesterday",c:"Jack Malik",t:"foco"},
{f:"Cuidar algo pequeño puede ayudarte a recuperar la esperanza en tu propia vida.",p:"The Secret Garden",c:"Mary Lennox",t:"animo"}
];
